openapi: 3.0.0
info:
  title: OpenWeatherMap - Fixed London
  version: 1.0.0
paths:
  /weather:
    get:
      parameters:
        - name: q
          in: query
          required: true
          schema: 
            type: string
            default: "London,uk"  # Critical for Informatica
          example: "London,uk"
        - name: APPID
          in: query
          required: true
          schema: {type: string}
      responses:
        '200':
          description: Success
servers:
  - url: https://api.openweathermap.org/data/2.5
