openapi: 3.0.0
info:
  title: Alpha Vantage Simplified
  version: 1.0.0
servers:
  - url: https://www.alphavantage.co
paths:
  /query:
    get:
      summary: Get stock data
      parameters:
        - name: function
          in: query
          required: true
          schema:
            type: string
          example: TIME_SERIES_INTRADAY
        - name: symbol
          in: query
          required: true
          schema:
            type: string
          example: IBM
        - name: apikey
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string