openapi: 3.0.0
info:
  title: Alpha Vantage API
  version: 1.0.0
servers:
  - url: https://www.alphavantage.co
paths:
  /query:
    get:
      summary: Get stock time series data
      parameters:
        - name: function
          in: query
          required: true
          schema:
            type: string
          example: TIME_SERIES_INTRADAY
        - name: symbol
          in: query
          required: true
          schema:
            type: string
          example: IBM
        - name: interval
          in: query
          schema:
            type: string
          example: 5min
        - name: apikey
          in: query
          required: true
          schema:
            type: string
        - name: datatype
          in: query
          schema:
            type: string
          example: csv
      responses:
        '200':
          description: CSV data
          content:
            text/csv:
              schema:
                type: string